version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - martin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  martin:
    image: urbica/martin
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: timescale/timescaledb-postgis
    restart: unless-stopped
    env_file:
      - .env
