version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - martin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  martin:
    image: urbica/martin
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres@db/db
    depends_on:
      - db

  db:
    image: timescale/timescaledb-postgis
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/data
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
